# Generated by Django 5.2.3 on 2025-06-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_todos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
